/*
	ESCRIBIR CONSULTAS CON BUEN DESEMPEÑO
	LA INDEXACION EN SQL Server
	FUNAMENTOS DE INDICE DE SERVIDOR SQL: INDICES AGRUPADOS(CLUSTERED), INDICES NO AGRUPADOS(NONCLUSTERED)
	LOS INDICES DE SQL Server: CONSIDERACIONES SOBRE EL RENDIMIENTO
	ESTADISTICAS DE DISTRIBUCION
	DEFINICION DE CURSORES
	EVITAR CURSORES
	VERIFICAR CON PLANES DE EJECUCION
	SET STATISTICS IO, TIME ON;
*/

USE Northwind;
GO

--EFICIENCIA EN PLANES DE EJECUCION
--INDEX SEEK
--MERGE JOIN (DATOS DE LAS DOS TABLAS DEBEN ESTAR ORDENADOS)

