USE Northwind;
GO

SELECT	I.name AS IndexName,
		OBJECT_NAME(IC.OBJECT_ID) AS TableName,
		COL_NAME(IC.OBJECT_ID, IC.COLUMN_ID) AS ColumName
FROM sys.indexes AS I
INNER JOIN sys.index_columns AS IC ON I.OBJECT_ID = IC.OBJECT_ID 
AND I.INDEX_ID = IC.INDEX_ID AND I.IS_PRIMARY_KEY = 1
GO

SELECT * FROM sys.views
GO

SP_HELPTEXT Invoices
GO

SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
GO

SELECT VIEW_CATALOG, VIEW_SCHEMA, VIEW_NAME, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.VIEW_COLUMN_USAGE;
GO

SELECT @@VERSION AS SQL_VERSION
SELECT SERVERPROPERTY('ProductVersion') AS [Version]
SELECT SERVERPROPERTY('Collation') AS [Collation]
GO

SP_HELPDB Northwind;
GO
SP_HELP Customers;
GO
SP_WHO2
GO
SP_LOCK
GO