/*
	UNA TRANSACCION ES UN GRUPO DE TAREAS QUE DEFINEN UNA UNIDAD DE TRABAJO
	TODA LA UNIDAD DEBE TENER EXITO O FALLAN JUNTAS, NO SE PERMITE UNA TERMINACION PARCIAL
	SE PUEDEN ADMINISTRAR CON LAS SIGUIENTES INSTRUCCIONES: BEGIN/COMMIT/ROLLBACK TRANSACTION
	
	EJ:
		BEGIN TRY
			BEGIN TRANSACTION
				INSERT INTO Orders ...
				INSERT INTO OrderDetails ...
			COMMIT TRANSACTION
		END TRY
		BEGIN CATCH
			SELECT ERROR_NUMBER() AS NumeroError,
			ERROR_SEVERITY() AS NumeroSeveridad,
			ERROR_STATE() AS NumeroEstado,
			ERROR_PROCEDURE() AS ProcedimientoDelError,
			ERROR_MESSAGE() AS MensajeError
			ROLLBACK TRANSACTION
		END CATCH
*/

USE Northwind;
GO

--VER LOS BLOQUEOS SOBRE OBJETOS DE LA BBDD
SP_LOCK

--DECLARAR TRANSACCION
BEGIN TRAN
	INSERT INTO Customers (CustomerID, CompanyName, ContactName, ContactTitle, Country)
	VALUES ('VHCV1', 'VISOALGT', 'JOSE', 'ING.', 'REP DOM')
GO

--DESCHACER LA TRANSACCION 
ROLLBACK TRAN

--CONFIRMAR LA TRANSACCION
COMMIT TRAN

--VER EL REGISTRO CON OTRO USUARIO

SELECT * FROM Customers WHERE CustomerID = 'VHCV1'


---XACT_ABORT: SENTENCIA QUE SE UTILIZA PARA CUANDO HAY UN FALLO EN UNA TRANSACCION ACTUE COMO ROLLBACK, AUNQUE SE USE COMMIT
SET XACT_ABORT ON;

BEGIN TRANSACTION
	INSERT INTO [Order Details] (OrderID, ProductID, UnitPrice, Quantity, Discount)
	VALUES (10248, 22, 11.50, 12, 0)

	INSERT INTO [Order Details] (OrderID, ProductID, UnitPrice, Quantity, Discount)
	VALUES (10248, 22, 11.50, 12, 0)

	INSERT INTO [Order Details] (OrderID, ProductID, UnitPrice, Quantity, Discount)
	VALUES (10249, 22, 11.50, 12, 0)
COMMIT TRANSACTION
GO

SELECT * FROM [Order Details]
GO


